// <auto-generated />
using System;
using DoofenshmirtzsWebShop.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoofenshmirtzsWebShop.Migrations
{
    [DbContext(typeof(DoofenshmirtzWebShopContext))]
    partial class DoofenshmirtzWebShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Address", b =>
                {
                    b.Property<int>("addressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("addressCountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("addressCustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("addressPostalCode")
                        .HasColumnType("int");

                    b.Property<string>("addressStreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("addressID");

                    b.HasIndex("userID");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            addressID = 1,
                            addressCountryName = "Carkeys",
                            addressCustomerName = "Test McTesting",
                            addressPostalCode = 6969,
                            addressStreetName = "Danville 101",
                            userID = 1
                        });
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("categoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryName = "Products"
                        },
                        new
                        {
                            categoryID = 2,
                            categoryName = "Books"
                        },
                        new
                        {
                            categoryID = 3,
                            categoryName = "Merch"
                        });
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("orderID");

                    b.HasIndex("userID");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            orderID = 1,
                            orderDate = new DateTime(2021, 9, 17, 14, 30, 46, 990, DateTimeKind.Local).AddTicks(3747),
                            userID = 1
                        },
                        new
                        {
                            orderID = 2,
                            orderDate = new DateTime(2021, 9, 17, 14, 30, 46, 992, DateTimeKind.Local).AddTicks(3024),
                            userID = 2
                        },
                        new
                        {
                            orderID = 3,
                            orderDate = new DateTime(2021, 9, 17, 14, 30, 46, 992, DateTimeKind.Local).AddTicks(3055),
                            userID = 2
                        });
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryID")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(3200)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("productPrice")
                        .HasColumnType("int");

                    b.Property<int>("productStock")
                        .HasColumnType("int");

                    b.HasKey("productID");

                    b.HasIndex("categoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            productID = 1,
                            categoryID = 1,
                            productDescription = "Tired of listening to meaningless things all the time? try blasting them with this gun and you'll never have to hear them again!",
                            productName = "The I-Don't-Care-Inator",
                            productPrice = 49,
                            productStock = 7
                        },
                        new
                        {
                            productID = 2,
                            categoryID = 1,
                            productDescription = "Dr. Heinz Doofenshmirtz' no. 1 guide to everything you need to know about being evil!",
                            productName = "Kill-half-the-people-in-the-world-with-a-snap-Inator",
                            productPrice = 299,
                            productStock = 2
                        },
                        new
                        {
                            productID = 3,
                            categoryID = 1,
                            productDescription = "Support your local evil branch with this T-shirt!",
                            productName = "Shut-The-Hell-Up-Inator",
                            productPrice = 50,
                            productStock = 8
                        });
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.ProductImage", b =>
                {
                    b.Property<int>("productImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.Property<string>("productImageImage")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<string>("productImageImageDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("productImageID");

                    b.HasIndex("productID");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userRole")
                        .HasColumnType("int");

                    b.HasKey("userID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            userID = 1,
                            userEmail = "test@test.dk",
                            userName = "Test101",
                            userPassword = "Test1234",
                            userRole = 1
                        },
                        new
                        {
                            userID = 2,
                            userEmail = "perry@platypus.dk",
                            userName = "Perry",
                            userPassword = "Doofenia",
                            userRole = 1
                        });
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Address", b =>
                {
                    b.HasOne("DoofenshmirtzsWebShop.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Order", b =>
                {
                    b.HasOne("DoofenshmirtzsWebShop.Database.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Product", b =>
                {
                    b.HasOne("DoofenshmirtzsWebShop.Database.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.ProductImage", b =>
                {
                    b.HasOne("DoofenshmirtzsWebShop.Database.Entities.Product", "product")
                        .WithMany("ImageList")
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("DoofenshmirtzsWebShop.Database.Entities.Product", b =>
                {
                    b.Navigation("ImageList");
                });
#pragma warning restore 612, 618
        }
    }
}
